Description: Backup Plan template to take backup of assigned resources daily at 12pm

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Encryption key for for BackupPlanWithDailyBackUps"
      EnableKeyRotation: True
      Enabled: True
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:  
              - "AWS":  { "AWS": "arn:aws:iam::092941714243:role/administrators"}  
            Action: 
              - kms:*
            Resource: "*"

  BackupVaultWithDailyBackups:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "BackupVaultWithDailyBackups"
      EncryptionKeyArn: !GetAtt KMSKey.Arn

  BackupPlanWithDailyBackups:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: "BackupPlanWithDailyBackups"
        AdvancedBackupSettings:
          - ResourceType: EC2
        BackupPlanRule:
          -
            RuleName: "DailyBackups"
            TargetBackupVault: !Ref BackupVaultWithDailyBackups
            ScheduleExpression: "cron(0 0 12 * * ?)"
            #LifecycleResourceType: 
                 #DeleteAfterDays: 365
                 #MoveToColdStorageAfterDays: 7
    DependsOn: BackupVaultWithDailyBackups

  BackupRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2020-02-01"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "backup.amazonaws.com"
            Action:
              - "sts:AssumeRole"      
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"
            
  TagBasedBackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupPlanId: !Ref BackupPlanWithDailyBackups
      BackupSelection: 
        SelectionName: "TagBasedBackupSelection"
        IamRoleArn: !GetAtt BackupRole.Arn
        ListOfTags: 
          - ConditionType: "STRINGEQUALS"
            ConditionKey: "backup"
            ConditionValue: "test"
    DependsOn: BackupPlanWithDailyBackups



    